api_key:
  transactions_by_channel: <%= ENV['TRANSACTIONS_BY_CHANNEL_KEY'] %>
  completion_rate: <%= ENV['COMPLETION_RATE_KEY'] %>

_id:
  paper_count_uuid: <%= ENV['PAPER_COUNT_UUID'] %>
  digital_count_uuid: <%= ENV['DIGITAL_COUNT_UUID'] %>
  complete_count_uuid: <%= ENV['COMPLETE_COUNT_UUID'] %>
  start_count_uuid: <%= ENV['START_COUNT_UUID'] %>
